CREATE TABLE doc_sequences (
  id INT AUTO_INCREMENT PRIMARY KEY,
  doc_type VARCHAR(50) NOT NULL,
  prefix VARCHAR(50) NOT NULL,
  current_no INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY unique_doc_type (doc_type)
) ENGINE=InnoDB;
